import { type NextPage } from "next";
import Head from "next/head";
import {SignIn, useUser, SignOutButton} from '@clerk/nextjs'
const Home: NextPage = () => {
  const {user} = useUser()
  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="flex min-h-screen flex-col items-center justify-center bg-gradient-to-b from-[#252525] to-[#141414]">
        <div className="container flex flex-col items-center justify-center gap-12 px-4 py-16 ">
          <h1 className="text-5xl font-extrabold tracking-tight text-white sm:text-[5rem]">
           Welcome to <span className="text-[hsl(36,67%,38%)]">Aurum</span> Bank
          </h1>
          <div className="grid grid-cols-1 gap-4 md:gap-8">
              <div className="text-lg">
                {!!user || user !== null ? <SignOutButton/> : <SignIn afterSignInUrl={"user-profile"}/>} 
              </div>
          </div>
        </div>
      </main>
    </>
  )
}
export default Home
